import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import { scanForSkills, type ExperienceFile } from "./skill-scan.js";
import type { SkillCluster } from "./types.js";

// ─── Constants ──────────────────────────────────────────────────────────────

const VAULT_PATH = join(homedir(), "Obsidian Vault");
const EXPERIENCES_DIR = join(VAULT_PATH, "Experiences");
const CANDIDATES_FILE = join(VAULT_PATH, "Skill-Candidates", "SKILL-CANDIDATES.md");
const SKILL_INDEX_FILE = join(VAULT_PATH, "Skill-Candidates", "SKILL-INDEX.md");

// ─── Helpers ────────────────────────────────────────────────────────────────

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function parsePreviousCounts(content: string): { counts: Map<string, number>; previousDate: string | null } {
  const counts = new Map<string, number>();
  const dateMatch = content.match(/date:\s*(\S+)/);
  const previousDate = dateMatch ? dateMatch[1] : null;
  const clusterRegex = /###\s+(\S+)\s+\((\d+)\s+experiences?\)/g;
  let match;
  while ((match = clusterRegex.exec(content)) !== null) {
    counts.set(match[1], parseInt(match[2]));
  }
  return { counts, previousDate };
}

function parseExistingSkills(content: string): Set<string> {
  const skills = new Set<string>();
  const regex = /###\s+(\S+)\s+\(\d+\s+experiences?\)[^]*?has skill/gi;
  let match;
  while ((match = regex.exec(content)) !== null) {
    skills.add(match[1].toLowerCase());
  }
  return skills;
}

// ─── Runner ─────────────────────────────────────────────────────────────────

export interface SkillScanPipelineResult {
  clusters: number;
  pendingProposals: number;
  approaching: number;
}

/**
 * Full skill-scan pipeline: read experiences from vault, run scan, write SKILL-CANDIDATES.md.
 */
export function runSkillScanPipeline(): SkillScanPipelineResult {
  if (!existsSync(EXPERIENCES_DIR)) {
    return { clusters: 0, pendingProposals: 0, approaching: 0 };
  }

  // Read experience files
  const files = readdirSync(EXPERIENCES_DIR).filter((f) => f.endsWith(".md"));
  const experienceFiles: ExperienceFile[] = [];
  for (const file of files) {
    try {
      const content = readFileSync(join(EXPERIENCES_DIR, file), "utf8");
      experienceFiles.push({ name: file.replace(".md", ""), content });
    } catch { /* skip unreadable */ }
  }

  // Read previous scan state
  let previousCounts = new Map<string, number>();
  let previousDate: string | null = null;
  if (existsSync(CANDIDATES_FILE)) {
    try {
      const parsed = parsePreviousCounts(readFileSync(CANDIDATES_FILE, "utf8"));
      previousCounts = parsed.counts;
      previousDate = parsed.previousDate;
    } catch { /* ignore */ }
  }

  // Read existing skills
  let existingSkills = new Set<string>();
  if (existsSync(SKILL_INDEX_FILE)) {
    try {
      existingSkills = parseExistingSkills(readFileSync(SKILL_INDEX_FILE, "utf8"));
    } catch { /* ignore */ }
  }

  // Run the scan
  const result = scanForSkills(experienceFiles, previousCounts);

  // Write SKILL-CANDIDATES.md
  writeCandidatesFile(result.clusters, previousCounts, previousDate, existingSkills);

  // Write pending proposals marker
  const newClusters = result.clusters.filter((c) => c.status === "new");
  if (newClusters.length > 0) {
    const markerPath = join(VAULT_PATH, ".skill-proposals-pending.json");
    const proposals = newClusters.map((c) => ({ tag: c.tag, count: c.count, files: c.files, date: today() }));
    writeFileSync(markerPath, JSON.stringify(proposals, null, 2));
  }

  return {
    clusters: result.clusters.length,
    pendingProposals: result.pendingProposals,
    approaching: result.approaching,
  };
}

function writeCandidatesFile(
  clusters: SkillCluster[],
  previousCounts: Map<string, number>,
  previousDate: string | null,
  existingSkills: Set<string>,
): void {
  let md = `---\ndate: ${today()}\ntype: skill-scan\nprevious-scan: ${previousDate || "none"}\n---\n\n`;
  md += `# Skill Candidates\n\n`;
  md += `> Auto-generated by open-brain skill-scan on ${today()}.\n`;
  md += `> Clusters of 3+ experiences suggest a reusable skill could be distilled.\n\n`;
  md += `## By Tag\n\n`;

  for (const cluster of clusters) {
    const hasSkill = existingSkills.has(cluster.tag.toLowerCase());
    const status: string[] = [];
    if (hasSkill) status.push("has skill");
    if (cluster.status === "new") status.push("NEW");
    if (cluster.status === "growing") status.push("growing");
    if (cluster.consolidatedFrom?.length) status.push(`merged: ${cluster.consolidatedFrom.join(", ")}`);

    md += `### ${cluster.tag} (${cluster.count} experiences)${status.length ? " — " + status.join(", ") : ""}\n\n`;
    if (hasSkill) {
      md += `**Status:** Skill exists — consider updating if new experiences add novel patterns\n\n`;
    } else {
      md += `**Potential skill:** "${cluster.tag}" patterns and gotchas\n\n`;
    }
    for (const f of cluster.files) {
      md += `- [[${f}]]\n`;
    }
    md += "\n";
  }

  if (previousDate) {
    md += `## Scan Diff (vs ${previousDate})\n\n`;
    md += `| Cluster | Previous | Current | Change |\n|---|---|---|---|\n`;
    const allTags = new Set([...previousCounts.keys(), ...clusters.map((c) => c.tag)]);
    for (const tag of [...allTags].sort()) {
      const prev = previousCounts.get(tag) ?? 0;
      const curr = clusters.find((c) => c.tag === tag)?.count ?? 0;
      if (curr < 3 && prev < 3) continue;
      const change = prev === 0 ? "NEW" : curr === prev ? "unchanged" : `+${curr - prev}`;
      md += `| ${tag} | ${prev || "—"} | ${curr} | ${change} |\n`;
    }
    md += "\n";
  }

  md += `---\n\n*Last scan: ${today()}. Runs automatically at session end via open-brain pipeline.*\n`;

  writeFileSync(CANDIDATES_FILE, md);
}
