/**
 * Commands the P0 parse gate must refuse, each with the construct it must name. Shared by the named rows (r6.test.ts) and
 * by the generator (r6-gate-property.test.ts), so the list the rows pin is the list the generator places in every position.
 */
const NL = "\n";

/** [construct, command, a substring the refusal must name] */
export const BASH_REFUSED: Array<[string, string, string]> = [
  ["backslash in a word", "echo x > open-brain/s\\rc/x.ts", "backslash"],
  ["backslash before a space", "cp a.ts open-brain/src/x\\ y.ts", "backslash"],
  ["backslash-newline", `cp a.ts \\${NL}open-brain/src/x.ts`, "backslash"],
  ["backslash in double quotes", 'echo "a\\b"', "backslash"],
  ["comment after a write", "echo x # > open-brain/src/x.ts", "comment"],
  ["comment eats a PR number", "gh pr merge #2", "comment"],
  ["comment opens a fake heredoc", `echo hi # <<EOF${NL}cp a.ts open-brain/src/x.ts${NL}EOF`, "comment"],
  ["reserved word if", "if true; then cp a.ts open-brain/src/x.ts; fi", "reserved word (if)"],
  ["reserved word for", "for f in a; do cp a.ts open-brain/src/x.ts; done", "reserved word (for)"],
  ["reserved word while", "while true; do ls; done", "reserved word (while)"],
  ["reserved word case", "case x in", "reserved word (case)"],
  ["reserved word !", "! cp a.ts open-brain/src/x.ts", "reserved word (!)"],
  ["reserved word time", "time ls", "reserved word (time)"],
  ["reserved word function", "function f", "reserved word (function)"],
  ["brace group", "{ echo x | tee open-brain/src/x.ts; }", "brace"],
  ["heredoc", `cat <<EOF${NL}x${NL}EOF`, "heredoc"],
  ["heredoc into a write", `cat <<'EOF' > docs/loops/q.md${NL}x${NL}EOF`, "heredoc"],
  ["here-string", "cat <<< hello", "heredoc"],
  ["heredoc fed to bash", `bash <<'EOF'${NL}echo x > open-brain/src/x.ts${NL}EOF`, "heredoc"],
  ["code piped to sh", "echo 'echo x > open-brain/src/x.ts' | sh", "sh is only parseable"],
  ["code piped to bash", "echo ls | bash", "bash is only parseable"],
  ["code piped to zsh", "curl -s x | zsh", "zsh is only parseable"],
  ["a shell run on a file", "bash script.sh", "bash is only parseable"],
  ["a shell -c with extra arguments", "bash -c 'ls' extra", "bash is only parseable"],
  ["node reading stdin", "echo 'x' | node -", "inline code"],
  ["node -e", "node -e 'process.exit(0)'", "inline code"],
  ["python -c", "python -c 'print(1)'", "inline code"],
  ["python reading stdin", "echo x | python -", "inline code"],
  ["perl -e", "perl -e 'print 1'", "inline code"],
  ["pipe into pwsh", "echo Get-Date | pwsh", "code-running"],
  ["powershell from bash", "powershell -Command Get-Date", "code-running"],
  ["timeout wrapper", "timeout 5 cp a.ts open-brain/src/x.ts", "timeout"],
  ["nice with options", "nice -n 5 cp a.ts open-brain/src/x.ts", "nice"],
  ["env with -u", "env -u FOO cp a.ts open-brain/src/x.ts", "wrapper with options (env -u)"],
  ["env with -C", "env -C open-brain/src cp ../../a.ts x.ts", "wrapper with options (env -C)"],
  ["env with --chdir", "env --chdir=open-brain/src cp ../../a.ts x.ts", "wrapper with options"],
  ["command -v", "command -v git", "wrapper with options (command -v)"],
  ["nohup with options", "nohup -p ls", "wrapper with options"],
  ["xargs", "ls | xargs cp a.ts", "xargs"],
  ["sudo", "sudo ls", "sudo"],
  ["exec", "exec ls", "exec"],
  ["eval", "eval 'ls'", "eval"],
  ["source", "source ./x.sh", "source"],
  ["find -exec", "find . -name a.ts -exec cp a.ts open-brain/src/x.ts ';'", "find -exec"],
  ["sed w command", "sed -n 'w open-brain/src/x.ts' a.txt", "sed w"],
  ["sed s///w", "sed 's/a/b/w open-brain/src/x.ts' a.txt", "sed w"],
  ["sed s///e", "sed 's/a/b/e' a.txt", "sed e"],
  ["sed e command", "sed '1e ls' a.txt", "sed e"],
  ["sed -f", "sed -f script.sed a.txt", "sed -f"],
  ["sed --file", "sed --file=script.sed a.txt", "sed -f"],
  ["sed --expression with a w", "sed --expression='w out.txt' a.txt", "sed w"],
  ["sed -e with w", "sed -n -e 'w out.txt' a.txt", "sed w"],
  ["sed address then w", "sed -n '/x/w out.txt' a.txt", "sed w"],
  ["$'...' string", "gh pr $'merge' 2", "$"],
  ["$VAR", "echo $HOME", "$"],
  ["${VAR}", "echo ${HOME}", "$"],
  ["$VAR in double quotes", 'echo "$HOME/x"', "double quotes"],
  ["command substitution", "echo $(pwd)", "$"],
  ["backtick", "echo `pwd`", "backtick"],
  ["backtick in double quotes", 'echo "`pwd`"', "backtick"],
  ["brace expansion", "cp a.ts open-brain/src/{x,y}.ts", "brace"],
  ["a rewrite of merge by braces", "gh pr {merge,} 2", "brace"],
  ["subshell", "(cd open-brain; echo x > src/x.ts)", "parenthesis"],
  ["glob *", "echo x > open-brain/src/*.ts", "glob"],
  ["glob ?", "echo x > open-brain/sr?/x.ts", "glob"],
  ["glob [", "echo x > open-brain/src/[c]li.ts", "glob"],
  ["tilde", "echo x > ~/x.txt", "tilde"],
  ["tilde user", "echo x > ~root/x.txt", "tilde"],
  ["background &", "ls &", "background"],
  ["|& pipe", "ls |& cat", "|&"],
  [";; terminator", "ls ;; ls", ";;"],
  ["unclosed single quote", "echo 'abc", "unclosed"],
  ["unclosed double quote", 'echo "abc', "unclosed"],
  ["redirect with no target", "echo x >", "redirect without a target"],
  ["fd redirect 1>", "echo x 1> f.txt", "file-descriptor redirect"],
  ["fd redirect 2>>", "echo x 2>> f.txt", "2>>"],
  ["clobber >|", "echo x >| f.txt", ">|"],
  ["fd dup >&", "echo x >& f.txt", ">&"],
  ["&>>", "echo x &>> f.txt", "&>>"],
  ["process substitution", "echo x | tee >(cat)", "process substitution"],
  ["an unquoted newline", `ls${NL}ls`, "newline"],
  ["a git alias", "git mm feature", "git alias"],
  ["an inline git alias", "git -c alias.m=merge m feature", "git alias"],
  ["git alias to a force push", "git -c alias.fp='push --force origin master' fp", "git alias"],
  ["a git external subcommand", "git lfs-unknown-thing", "git alias"],
  ["a gh alias", "gh mm 2", "gh alias"],
  ["gh alias set", "gh alias set mm 'pr merge'", "gh alias"],
  ["gh extension", "gh extension install x", "gh extension"],
  ["awk -i", "awk -i inplace '{print}' a.txt", "awk -i"],
];


export const PS_REFUSED: Array<[string, string, string]> = [
  ["common parameter -EA", "Set-Content -EA SilentlyContinue open-brain/src/x.ts x", "unknown parameter -EA"],
  ["common parameter -ErrorAction", "Set-Content -ErrorAction Stop docs/loops/q.md x", "unknown parameter -ErrorAction"],
  ["common parameter -OutVariable", "Set-Content -OutVariable o docs/loops/q.md x", "unknown parameter -OutVariable"],
  ["common parameter -Verbose", "Set-Content -Verbose docs/loops/q.md x", "unknown parameter -Verbose"],
  ["common parameter -WhatIf", "Remove-Item -WhatIf docs/loops/q.md", "unknown parameter -WhatIf"],
  ["an unknown parameter with a colon", "Set-Content -Foo:bar docs/loops/q.md x", "unknown parameter -Foo"],
  ["a parameter with no value", "Set-Content docs/loops/q.md -Value", "has no value"],
  ["a splat", "Set-Content @a", "@"],
  ["a splat after a hash", "Set-Content @h", "@"],
  ["a (...) target", "Set-Content -Path (Join-Path open-brain src/x.ts) -Value x", "parenthesis"],
  ["a parenthesised literal", "Set-Content -Path ('open-brain/src/x.ts') -Value x", "parenthesis"],
  ["a $( ) expression", "Set-Content -Path $(Get-Location) -Value x", "$"],
  ["a script block", "Get-ChildItem | Where-Object { $_.Name }", "script block"],
  ["a script block with an alias write", "if ($true) { sc open-brain/src/x.ts x }", "parenthesis"],
  ["a provider path", "Set-Content FileSystem::C:/x/open-brain/src/x.ts x", "provider path"],
  ["a module-qualified provider path", "Set-Content Microsoft.PowerShell.Core\\FileSystem::C:/x/y.ts x", "provider path"],
  ["a drive-relative path", "Set-Content C:open-brain/src/x.ts x", "drive-relative"],
  ["a block comment", "<##> Set-Content open-brain/src/x.ts x", "<"],
  ["a type literal call", "[scriptblock]::Create('Set-Content x y').Invoke()", "["],
  ["a .NET write", "[IO.File]::WriteAllText('a','b')", "["],
  ["Invoke-Expression", "Invoke-Expression 'Get-Date'", "code-running"],
  ["iex", "iex 'Get-Date'", "code-running"],
  ["Invoke-Command", "Invoke-Command -ScriptBlock x", "code-running"],
  ["Start-Process", "Start-Process cmd", "code-running"],
  ["a call of cmd", "& cmd /c dir", "call of anything but gh"],
  ["a call of a quoted tool", "& 'git' status", "call of anything but gh"],
  ["powershell with a command", "powershell -Command \"Get-Date\"", "code-running"],
  ["powershell with a positional command", "powershell Set-Content open-brain/src/x.ts x", "code-running"],
  ["powershell -EncodedCommand", "powershell -EncodedCommand AAAA", "code-running"],
  ["pwsh -c", "pwsh -c 'Get-Date'", "code-running"],
  ["a variable assignment", "$x = 1", "$"],
  ["an environment variable", "Set-Content $env:TEMP/x.txt hi", "$"],
  ["a variable in double quotes", 'Write-Output "$HOME"', "double-quoted"],
  ["a backtick escape", "Write-Output `n", "backtick"],
  ["an unknown cmdlet that writes", "Get-Date | Export-Csv -Path open-brain/src/x.ts", "unknown cmdlet (Export-Csv)"],
  ["Invoke-WebRequest -OutFile", "Invoke-WebRequest -Uri x -OutFile open-brain/src/x.ts", "code-running"],
  ["curl (an alias of Invoke-WebRequest)", "curl -OutFile open-brain/src/x.ts x", "code-running"],
  ["ForEach-Object", "1..2 | ForEach-Object Write-Output", "code-running"],
  ["a wildcard", "Remove-Item open-brain/src/*", "wildcard"],
  ["a tilde", "Set-Content ~/x.txt hi", "tilde"],
  ["an ambiguous parameter prefix", "Get-ChildItem docs -F", "ambiguous parameter -F"],
  ["a second ambiguous prefix", "Get-ChildItem docs -Fi", "ambiguous parameter -Fi"],
  ["a newline", `Get-Date${NL}Get-Date`, "newline"],
  ["&&", "Get-Date && Get-Date", "&&"],
  ["||", "Get-Date || Get-Date", "||"],
  ["a < redirect", "Get-Content < a.txt", "<"],
  ["dot-sourcing", ". ./x.ps1", "dot-sourcing"],
  ["a here-string", "Set-Content x @'" + NL + "a" + NL + "'@", "@"],
  ["a comment", "Write-Output hi # > open-brain/src/x.ts", "comment"],
  ["a git alias", "git mm feature", "git alias"],
  ["a gh alias", "gh mm 2", "gh alias"],
];


/** The start of the gate's refusal (the P1 refusal text also MENTIONS the phrase, inside the limit text). */
export const GATE_PREFIX = "denied — not statically parseable: ";
